name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Create deployment archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifacts
      #     path: build

      - name: Deploy to server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
            cd /var/www/anirudhdayanand.live/K-Folio
            git pull origin main

            # # Unpack build artifacts
            # tar -xzvf build-artifacts.tar.gz

            npm install
            npm run build

            systemctl restart nginx
          EOF
